export const FETCH_TASKS_REQUEST = "FETCH_TASKS_REQUEST";
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
export const FETCH_TASKS_FAILURE = "FETCH_TASKS_FAILURE";

export const SET_PAGE = "SET_PAGE";
export const SORT_TASKS = "SORT_TASKS";

export const UPLOAD_TASK_REQUEST = "UPLOAD_TASK_REQUEST";
export const UPLOAD_TASK_SUCCESS = "UPLOAD_TASK_SUCCESS";
export const UPLOAD_TASK_FAILURE = "UPLOAD_TASK_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const EDIT_TASK_REQUEST = "EDIT_TASK_REQUEST";
export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS";
export const EDIT_TASK_FAILURE = "EDIT_TASK_FAILURE";
